### ISSUE TITLE
mejs fails to load webm video in Opera.

### ISSUE THREAD

**Issue by stephenwithav** [teambition/mejs#1]
See: the [What Our Clients Say](http://catchtalent.com/employer-brand-services/) section of the page.

    Media error: Format(s) not supported or source(s) not found
    mejs.download-file: http://catchtalent.com/wp-content/uploads/2017/02/bokeh2-Stock-video_1.mp4
    mejs.download-file: http://catchtalent.com/wp-content/uploads/2017/02/bokeh2-Stock-video.webm

Both videos exist.  The `webm` file will play in Opera if you load the URL directly.

**Comment by nekolab** [comment]
Hi
I believe the `mejs` you mentioned belongs to this project: [mediaelement](https://github.com/mediaelement/mediaelement)
You need file the issue on their tracker instead

**Comment by stephenwithav** [comment]
I feel stupid now. :D 

Thank you for pointing out my error.
